/* Adapted from stu-code/sas utility-macros/split_data.sas
   The %split_data macro chunks a dataset into N pieces of roughly equal
   size by reading the row count, then computing firstobs/obs offsets
   for each piece. The arithmetic at the heart of the macro is:

       firstobs(s) = floor( n - (n/N)*(N - s + 1) + 1 )
       obs(s)      = floor( n - (n/N)*(N - s)         )

   for split s in [1..N], where n is the input row count.

   This bundle exercises the same logic with sashelp.class (19 rows, N=4):
       split 1: rows 1-5   (5 rows)
       split 2: rows 6-10  (5 rows)
       split 3: rows 11-15 (5 rows)
       split 4: rows 16-19 (4 rows)
   The offsets are static here rather than generated by the macro, but
   the boundary math is identical to what the macro produces. */

data class1; set sashelp.class(firstobs=1  obs=5 ); run;
data class2; set sashelp.class(firstobs=6  obs=10); run;
data class3; set sashelp.class(firstobs=11 obs=15); run;
data class4; set sashelp.class(firstobs=16 obs=19); run;

title "split_data math applied to sashelp.class (19 rows / N=4)";

proc print data=class1; title2 "Split 1: rows 1-5";   run;
proc print data=class2; title2 "Split 2: rows 6-10";  run;
proc print data=class3; title2 "Split 3: rows 11-15"; run;
proc print data=class4; title2 "Split 4: rows 16-19"; run;

/* Confirm row counts add up to the original 19 */
data all_pieces;
    set class1 class2 class3 class4;
run;

title2 "Row totals: should be 19 across all splits, no duplicates";
proc sql;
    select count(*) as n_total
      from all_pieces;
quit;
